--------------------------------------------------------
--  File created - Sunday-October-08-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GROUP_TBL
--------------------------------------------------------

  CREATE TABLE "REGISTRATION"."GROUP_TBL" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index GROUP_TBL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REGISTRATION"."GROUP_TBL_PK" ON "REGISTRATION"."GROUP_TBL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table GROUP_TBL
--------------------------------------------------------

  ALTER TABLE "REGISTRATION"."GROUP_TBL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "REGISTRATION"."GROUP_TBL" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "REGISTRATION"."GROUP_TBL" ADD CONSTRAINT "GROUP_TBL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
