--------------------------------------------------------
--  File created - Sunday-October-08-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TOKEN_TBL
--------------------------------------------------------

  CREATE TABLE "REGISTRATION"."TOKEN_TBL" 
   (	"TOKENID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EXPIRED" NUMBER(1,0), 
	"REVOKED" NUMBER(1,0), 
	"TOKEN" VARCHAR2(255 CHAR), 
	"TOKENTYPE" VARCHAR2(255 CHAR), 
	"USER_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008397
--------------------------------------------------------

  CREATE UNIQUE INDEX "REGISTRATION"."SYS_C008397" ON "REGISTRATION"."TOKEN_TBL" ("TOKENID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_L6KO6B9EOTYBAV782BBSLU1PM
--------------------------------------------------------

  CREATE UNIQUE INDEX "REGISTRATION"."UK_L6KO6B9EOTYBAV782BBSLU1PM" ON "REGISTRATION"."TOKEN_TBL" ("TOKEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TOKEN_TBL
--------------------------------------------------------

  ALTER TABLE "REGISTRATION"."TOKEN_TBL" MODIFY ("TOKENID" NOT NULL ENABLE);
  ALTER TABLE "REGISTRATION"."TOKEN_TBL" MODIFY ("EXPIRED" NOT NULL ENABLE);
  ALTER TABLE "REGISTRATION"."TOKEN_TBL" MODIFY ("REVOKED" NOT NULL ENABLE);
  ALTER TABLE "REGISTRATION"."TOKEN_TBL" ADD PRIMARY KEY ("TOKENID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "REGISTRATION"."TOKEN_TBL" ADD CONSTRAINT "UK_L6KO6B9EOTYBAV782BBSLU1PM" UNIQUE ("TOKEN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TOKEN_TBL
--------------------------------------------------------

  ALTER TABLE "REGISTRATION"."TOKEN_TBL" ADD CONSTRAINT "FKPLO6PWQ4CC66YWV7P5OJI4E2T" FOREIGN KEY ("USER_ID")
	  REFERENCES "REGISTRATION"."USER_TBL" ("USERID") ENABLE;
